import type { Metadata } from "next";

import "./globals.css";
import Header from "./Header/header";
import Footer from "./Footer/footes";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
      <Header/>
        <main className="w-full h-[700]">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
