import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-1 container mx-auto p-6">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html >
  );
}
